// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/proto/StreamEvent.proto

package com.unknown.vigor.gateway.common.protobuf;

public final class StreamEvent {
  private StreamEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code StatusCode}
   */
  public enum StatusCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>NULL = 0;</code>
     */
    NULL(0),
    /**
     * <code>SUCCESS = 200;</code>
     */
    SUCCESS(200),
    /**
     * <code>LOAD_FULL = 429;</code>
     */
    LOAD_FULL(429),
    /**
     * <pre>
     * 不需要进行重试
     * </pre>
     *
     * <code>BAD_REQUEST = 400;</code>
     */
    BAD_REQUEST(400),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>NULL = 0;</code>
     */
    public static final int NULL_VALUE = 0;
    /**
     * <code>SUCCESS = 200;</code>
     */
    public static final int SUCCESS_VALUE = 200;
    /**
     * <code>LOAD_FULL = 429;</code>
     */
    public static final int LOAD_FULL_VALUE = 429;
    /**
     * <pre>
     * 不需要进行重试
     * </pre>
     *
     * <code>BAD_REQUEST = 400;</code>
     */
    public static final int BAD_REQUEST_VALUE = 400;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static StatusCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static StatusCode forNumber(int value) {
      switch (value) {
        case 0: return NULL;
        case 200: return SUCCESS;
        case 429: return LOAD_FULL;
        case 400: return BAD_REQUEST;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<StatusCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        StatusCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<StatusCode>() {
            public StatusCode findValueByNumber(int number) {
              return StatusCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.unknown.vigor.gateway.common.protobuf.StreamEvent.getDescriptor().getEnumTypes().get(0);
    }

    private static final StatusCode[] VALUES = values();

    public static StatusCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private StatusCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:StatusCode)
  }

  public interface SimpleEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimpleEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string logId = 1;</code>
     * @return The logId.
     */
    java.lang.String getLogId();
    /**
     * <code>string logId = 1;</code>
     * @return The bytes for logId.
     */
    com.google.protobuf.ByteString
        getLogIdBytes();

    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    int getMetaCount();
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    boolean containsMeta(
        java.lang.String key);
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMeta();
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetaMap();
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    /* nullable */
java.lang.String getMetaOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    java.lang.String getMetaOrThrow(
        java.lang.String key);

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();

    /**
     * <code>int64 ctime = 5;</code>
     * @return The ctime.
     */
    long getCtime();
  }
  /**
   * Protobuf type {@code SimpleEvent}
   */
  public static final class SimpleEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SimpleEvent)
      SimpleEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimpleEvent.newBuilder() to construct.
    private SimpleEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimpleEvent() {
      logId_ = "";
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SimpleEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              logId_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                meta_ = com.google.protobuf.MapField.newMapField(
                    MetaDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              meta__ = input.readMessage(
                  MetaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              meta_.getMutableMap().put(
                  meta__.getKey(), meta__.getValue());
              break;
            }
            case 34: {

              data_ = input.readBytes();
              break;
            }
            case 40: {

              ctime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_SimpleEvent_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMeta();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_SimpleEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.class, com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.Builder.class);
    }

    public static final int LOGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object logId_;
    /**
     * <code>string logId = 1;</code>
     * @return The logId.
     */
    @java.lang.Override
    public java.lang.String getLogId() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logId_ = s;
        return s;
      }
    }
    /**
     * <code>string logId = 1;</code>
     * @return The bytes for logId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLogIdBytes() {
      java.lang.Object ref = logId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 3;
    private static final class MetaDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_SimpleEvent_MetaEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> meta_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMeta() {
      if (meta_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDefaultEntryHolder.defaultEntry);
      }
      return meta_;
    }

    public int getMetaCount() {
      return internalGetMeta().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    @java.lang.Override
    public boolean containsMeta(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMeta().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return getMetaMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
      return internalGetMeta().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    public static final int CTIME_FIELD_NUMBER = 5;
    private long ctime_;
    /**
     * <code>int64 ctime = 5;</code>
     * @return The ctime.
     */
    @java.lang.Override
    public long getCtime() {
      return ctime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, logId_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMeta(),
          MetaDefaultEntryHolder.defaultEntry,
          3);
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      if (ctime_ != 0L) {
        output.writeInt64(5, ctime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(logId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, logId_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMeta().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        meta__ = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, meta__);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      if (ctime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, ctime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent)) {
        return super.equals(obj);
      }
      com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent other = (com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent) obj;

      if (!getLogId()
          .equals(other.getLogId())) return false;
      if (!internalGetMeta().equals(
          other.internalGetMeta())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (getCtime()
          != other.getCtime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LOGID_FIELD_NUMBER;
      hash = (53 * hash) + getLogId().hashCode();
      if (!internalGetMeta().getMap().isEmpty()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMeta().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + CTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCtime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimpleEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimpleEvent)
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_SimpleEvent_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMeta();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMeta();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_SimpleEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.class, com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.Builder.class);
      }

      // Construct using com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        logId_ = "";

        internalGetMutableMeta().clear();
        data_ = com.google.protobuf.ByteString.EMPTY;

        ctime_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_SimpleEvent_descriptor;
      }

      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent getDefaultInstanceForType() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent build() {
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent buildPartial() {
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent result = new com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent(this);
        int from_bitField0_ = bitField0_;
        result.logId_ = logId_;
        result.meta_ = internalGetMeta();
        result.meta_.makeImmutable();
        result.data_ = data_;
        result.ctime_ = ctime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent) {
          return mergeFrom((com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent other) {
        if (other == com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent.getDefaultInstance()) return this;
        if (!other.getLogId().isEmpty()) {
          logId_ = other.logId_;
          onChanged();
        }
        internalGetMutableMeta().mergeFrom(
            other.internalGetMeta());
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        if (other.getCtime() != 0L) {
          setCtime(other.getCtime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object logId_ = "";
      /**
       * <code>string logId = 1;</code>
       * @return The logId.
       */
      public java.lang.String getLogId() {
        java.lang.Object ref = logId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          logId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string logId = 1;</code>
       * @return The bytes for logId.
       */
      public com.google.protobuf.ByteString
          getLogIdBytes() {
        java.lang.Object ref = logId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          logId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string logId = 1;</code>
       * @param value The logId to set.
       * @return This builder for chaining.
       */
      public Builder setLogId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        logId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string logId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLogId() {
        
        logId_ = getDefaultInstance().getLogId();
        onChanged();
        return this;
      }
      /**
       * <code>string logId = 1;</code>
       * @param value The bytes for logId to set.
       * @return This builder for chaining.
       */
      public Builder setLogIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        logId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> meta_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMeta() {
        if (meta_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetaDefaultEntryHolder.defaultEntry);
        }
        return meta_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMeta() {
        onChanged();;
        if (meta_ == null) {
          meta_ = com.google.protobuf.MapField.newMapField(
              MetaDefaultEntryHolder.defaultEntry);
        }
        if (!meta_.isMutable()) {
          meta_ = meta_.copy();
        }
        return meta_;
      }

      public int getMetaCount() {
        return internalGetMeta().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */

      @java.lang.Override
      public boolean containsMeta(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetMeta().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetaMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMeta() {
        return getMetaMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
        return internalGetMeta().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetaOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMeta().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetaOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMeta().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMeta() {
        internalGetMutableMeta().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */

      public Builder removeMeta(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableMeta().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMeta() {
        return internalGetMutableMeta().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      public Builder putMeta(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableMeta().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */

      public Builder putAllMeta(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMeta().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      private long ctime_ ;
      /**
       * <code>int64 ctime = 5;</code>
       * @return The ctime.
       */
      @java.lang.Override
      public long getCtime() {
        return ctime_;
      }
      /**
       * <code>int64 ctime = 5;</code>
       * @param value The ctime to set.
       * @return This builder for chaining.
       */
      public Builder setCtime(long value) {
        
        ctime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 ctime = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCtime() {
        
        ctime_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:SimpleEvent)
    }

    // @@protoc_insertion_point(class_scope:SimpleEvent)
    private static final com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent();
    }

    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SimpleEvent>
        PARSER = new com.google.protobuf.AbstractParser<SimpleEvent>() {
      @java.lang.Override
      public SimpleEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimpleEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimpleEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.unknown.vigor.gateway.common.protobuf.StreamEvent.SimpleEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.StatusCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    int getCodeValue();
    /**
     * <code>.StatusCode code = 1;</code>
     * @return The code.
     */
    com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode getCode();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();

    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    int getMetaCount();
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    boolean containsMeta(
        java.lang.String key);
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getMeta();
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getMetaMap();
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    /* nullable */
java.lang.String getMetaOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    java.lang.String getMetaOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      code_ = 0;
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                meta_ = com.google.protobuf.MapField.newMapField(
                    MetaDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              meta__ = input.readMessage(
                  MetaDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              meta_.getMutableMap().put(
                  meta__.getKey(), meta__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_Response_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetMeta();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.class, com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>.StatusCode code = 1;</code>
     * @return The enum numeric value on the wire for code.
     */
    @java.lang.Override public int getCodeValue() {
      return code_;
    }
    /**
     * <code>.StatusCode code = 1;</code>
     * @return The code.
     */
    @java.lang.Override public com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode getCode() {
      @SuppressWarnings("deprecation")
      com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode result = com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode.valueOf(code_);
      return result == null ? com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode.UNRECOGNIZED : result;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int META_FIELD_NUMBER = 3;
    private static final class MetaDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_Response_MetaEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> meta_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetMeta() {
      if (meta_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetaDefaultEntryHolder.defaultEntry);
      }
      return meta_;
    }

    public int getMetaCount() {
      return internalGetMeta().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */

    @java.lang.Override
    public boolean containsMeta(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMeta().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetaMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMeta() {
      return getMetaMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    @java.lang.Override

    public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
      return internalGetMeta().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; meta = 3;</code>
     */
    @java.lang.Override

    public java.lang.String getMetaOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMeta().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode.NULL.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMeta(),
          MetaDefaultEntryHolder.defaultEntry,
          3);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode.NULL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(msg_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetMeta().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        meta__ = MetaDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, meta__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response)) {
        return super.equals(obj);
      }
      com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response other = (com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response) obj;

      if (code_ != other.code_) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!internalGetMeta().equals(
          other.internalGetMeta())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      if (!internalGetMeta().getMap().isEmpty()) {
        hash = (37 * hash) + META_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMeta().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_Response_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMeta();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableMeta();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.class, com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.Builder.class);
      }

      // Construct using com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        internalGetMutableMeta().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response getDefaultInstanceForType() {
        return com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response build() {
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response buildPartial() {
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response result = new com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response(this);
        int from_bitField0_ = bitField0_;
        result.code_ = code_;
        result.msg_ = msg_;
        result.meta_ = internalGetMeta();
        result.meta_.makeImmutable();
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response) {
          return mergeFrom((com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response other) {
        if (other == com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        internalGetMutableMeta().mergeFrom(
            other.internalGetMeta());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int code_ = 0;
      /**
       * <code>.StatusCode code = 1;</code>
       * @return The enum numeric value on the wire for code.
       */
      @java.lang.Override public int getCodeValue() {
        return code_;
      }
      /**
       * <code>.StatusCode code = 1;</code>
       * @param value The enum numeric value on the wire for code to set.
       * @return This builder for chaining.
       */
      public Builder setCodeValue(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.StatusCode code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode getCode() {
        @SuppressWarnings("deprecation")
        com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode result = com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode.valueOf(code_);
        return result == null ? com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode.UNRECOGNIZED : result;
      }
      /**
       * <code>.StatusCode code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(com.unknown.vigor.gateway.common.protobuf.StreamEvent.StatusCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.StatusCode code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> meta_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMeta() {
        if (meta_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MetaDefaultEntryHolder.defaultEntry);
        }
        return meta_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableMeta() {
        onChanged();;
        if (meta_ == null) {
          meta_ = com.google.protobuf.MapField.newMapField(
              MetaDefaultEntryHolder.defaultEntry);
        }
        if (!meta_.isMutable()) {
          meta_ = meta_.copy();
        }
        return meta_;
      }

      public int getMetaCount() {
        return internalGetMeta().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */

      @java.lang.Override
      public boolean containsMeta(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetMeta().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMetaMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getMeta() {
        return getMetaMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      @java.lang.Override

      public java.util.Map<java.lang.String, java.lang.String> getMetaMap() {
        return internalGetMeta().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetaOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMeta().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      @java.lang.Override

      public java.lang.String getMetaOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetMeta().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMeta() {
        internalGetMutableMeta().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */

      public Builder removeMeta(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableMeta().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableMeta() {
        return internalGetMutableMeta().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */
      public Builder putMeta(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) {
  throw new NullPointerException("map value");
}

        internalGetMutableMeta().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; meta = 3;</code>
       */

      public Builder putAllMeta(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableMeta().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response();
    }

    public static com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.unknown.vigor.gateway.common.protobuf.StreamEvent.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleEvent_MetaEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SimpleEvent_MetaEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_MetaEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_MetaEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/proto/StreamEvent.proto\"\214\001\n\013S" +
      "impleEvent\022\r\n\005logId\030\001 \001(\t\022$\n\004meta\030\003 \003(\0132" +
      "\026.SimpleEvent.MetaEntry\022\014\n\004data\030\004 \001(\014\022\r\n" +
      "\005ctime\030\005 \001(\003\032+\n\tMetaEntry\022\013\n\003key\030\001 \001(\t\022\r" +
      "\n\005value\030\002 \001(\t:\0028\001\"\202\001\n\010Response\022\031\n\004code\030\001" +
      " \001(\0162\013.StatusCode\022\013\n\003msg\030\002 \001(\t\022!\n\004meta\030\003" +
      " \003(\0132\023.Response.MetaEntry\032+\n\tMetaEntry\022\013" +
      "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001*F\n\nStatus" +
      "Code\022\010\n\004NULL\020\000\022\014\n\007SUCCESS\020\310\001\022\016\n\tLOAD_FUL" +
      "L\020\255\003\022\020\n\013BAD_REQUEST\020\220\003B+\n)com.unknown.vi" +
      "gor.gateway.common.protobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SimpleEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimpleEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleEvent_descriptor,
        new java.lang.String[] { "LogId", "Meta", "Data", "Ctime", });
    internal_static_SimpleEvent_MetaEntry_descriptor =
      internal_static_SimpleEvent_descriptor.getNestedTypes().get(0);
    internal_static_SimpleEvent_MetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SimpleEvent_MetaEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Code", "Msg", "Meta", });
    internal_static_Response_MetaEntry_descriptor =
      internal_static_Response_descriptor.getNestedTypes().get(0);
    internal_static_Response_MetaEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_MetaEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
